name: '2b. F1 Ingestion CD'

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  ACR_NAME: 'acrafdap123987123'
  RESOURCE_GROUP: 'rg-afdap123987123'
  ACI_NAME: 'ci-f1-api-ingestion-afdap123987123'
  PYTHONUNBUFFERED: '1'
  AZURE_STORAGE_ACCOUNT_URL: 'https://samainafdap123987123.blob.core.windows.net'
  STORAGE_ACCOUNT_NAME: 'samainafdap123987123'
  CONTAINER_NAME: 'bronze'
  START_SEASON: '2014'
  END_SEASON: '2025'

jobs:
  build-and-push:
    name: 'Build, Push image to ACR. Run on ACI'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login via OIDC (Managed Identity)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up Python for Testing
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'src/ingestion/f1_api/requirements*.txt'

    - name: Install Test Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: src/ingestion/f1_api

    - name: Run Live Integration Tests
      env:
        PYTHONPATH: .
      run: |
        python -m pytest -v -m "integration"
      working-directory: src/ingestion/f1_api

    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${{ env.ACR_NAME }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push F1 Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/ingestion/f1_api/Dockerfile
        push: true
        tags: |
          ${{ env.ACR_NAME }}.azurecr.io/f1_api_ingestion:latest
          ${{ env.ACR_NAME }}.azurecr.io/f1_api_ingestion:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Get ACR Credentials
      id: acr_creds
      run: |
        ACR_PASSWORD=$(az acr credential show --name ${{ env.ACR_NAME }} --query "passwords[0].value" -o tsv)
        echo "::add-mask::$ACR_PASSWORD"
        echo "PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV

    - name: Update ACI to run latest image
      run: |
        az container create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.ACI_NAME }} \
          --image ${{ env.ACR_NAME }}.azurecr.io/f1_api_ingestion:${{ github.sha }} \
          --os-type Linux \
          --restart-policy Never \
          --cpu 0.5 \
          --memory 1.0 \
          --registry-login-server ${{ env.ACR_NAME }}.azurecr.io \
          --registry-username ${{ env.ACR_NAME }} \
          --registry-password ${{ env.PASSWORD }} \
          --assign-identity "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-f1-ingestion-afdap123987123" \
          --environment-variables PYTHONUNBUFFERED="1" START_SEASON=${{ env.START_SEASON }} END_SEASON=${{ env.END_SEASON }} AZURE_STORAGE_ACCOUNT_URL=${{ env.AZURE_STORAGE_ACCOUNT_URL }} STORAGE_ACCOUNT_NAME=${{ env.STORAGE_ACCOUNT_NAME }} CONTAINER_NAME=${{ env.CONTAINER_NAME }}

    - name: Stream Container Runtime Logs
      run: |
        echo "Waiting for the container to start and log streams..."
        az container logs \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.ACI_NAME }} \
          --follow