name: '4a. F1 Aggregation CI'

on:
  push:
    branches-ignore: [main]
    paths: ['src/aggregation/f1_to_gold/**']
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths: ['src/aggregation/f1_to_gold/**']

permissions:
  contents: read

jobs:
  pytest-validation:
    name: 'Unit Tests: Aggregation'
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python      
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'src/aggregation/f1_to_gold/requirements.txt'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: src/aggregation/f1_to_gold

    - name: Run Unit Tests
      env: { PYTHONPATH: . }
      run: python -m pytest -v
      working-directory: src/aggregation/f1_to_gold