name: '2. F1 Ingestion Container Deployment'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/ingestion/f1-api/**' 
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  ACR_NAME: 'acrafdap123987123'
  RESOURCE_GROUP: 'rg-afdap123987123'
  ACI_NAME: 'ci-f1-api-ingestion-afdap123987123' 

jobs:
  build-and-push:
    name: 'Build, Push image to ACR. Run on ACI'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login via OIDC (Managed Identity)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${{ env.ACR_NAME }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push F1 Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/ingestion/f1-api/Dockerfile
        push: true
        tags: |
          ${{ env.ACR_NAME }}.azurecr.io/f1-api-ingestion:latest
          ${{ env.ACR_NAME }}.azurecr.io/f1-api-ingestion:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update ACI to run latest image
      run: |
        az container create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.ACI_NAME }} \
          --image ${{ env.ACR_NAME }}.azurecr.io/f1-api-ingestion:${{ github.sha }}