name: '1b. Core Infrastructure Destroy'

on:
  workflow_dispatch:
    inputs:
      environment_version:
        description: 'WHICH ENVIRONMENT DO YOU WANT TO DESTROY? (v1, v2)'
        required: true
        type: choice
        options:
          - 'v1'
          - 'v2'

permissions:
  contents: read
  id-token: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  terraform-destroy:
    name: 'Terraform Destroy (${{ github.event.inputs.environment_version }})'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true
      VERSION: ${{ github.event.inputs.environment_version }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.0

    - name: Terraform Init
      run: terraform init -reconfigure
      working-directory: ./infra/env/${{ env.VERSION }}

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ./infra/env/${{ env.VERSION }}